---

- hosts: all
  become: true
  tasks:

    - name: install updates (Ubuntu)
      package:
        update_only: yes
        update_cache: yes

- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php
      package:
        name: "{{ apache_package }}"
        state: latest